hl.bind("SUPER + slash", hl.dsp.submap("Apply Shader [G, R, P, V, O]"))
hl.define_submap("Apply Shader [G, R, P, V, O]", function()
    hl.bind("Z", function ()
            hl.dispatch(hl.dsp.exec_cmd("/home/tisupe/.config/hypr/scripts/zen"))
            hl.dispatch(hl.dsp.submap("reset"))
        end)
    hl.bind("R", function ()
            hl.dispatch(hl.dsp.exec_cmd("/home/tisupe/.config/hypr/scripts/retro"))
            hl.dispatch(hl.dsp.submap("reset"))
        end)
    hl.bind("P", function ()
            hl.dispatch(hl.dsp.exec_cmd("/home/tisupe/.config/hypr/scripts/paper"))
            hl.dispatch(hl.dsp.submap("reset"))
        end)
    hl.bind("V", function ()
            hl.dispatch(hl.dsp.exec_cmd("/home/tisupe/.config/hypr/scripts/vibrance"))
            hl.dispatch(hl.dsp.submap("reset"))
        end)
    hl.bind("O", function ()
            hl.dispatch(hl.dsp.exec_cmd("/home/tisupe/.config/hypr/scripts/oled-saver"))
            hl.dispatch(hl.dsp.submap("reset"))
    end)
    hl.bind("escape", hl.dsp.submap("reset"))
    hl.bind("backspace", hl.dsp.submap("reset"))
end)
