#!/bin/bash

DECO_FILE="/home/tisupe/.config/hypr/decoration.lua"
ANI_FILE="/home/tisupe/.config/hypr/animation.lua"

DECO_REQ='require("decorations.zen")'
ANI_REQ='require("animations.zen")'

if grep -qF "$DECO_REQ" "$DECO_FILE"; then
    sed -i "/$DECO_REQ/d" "$DECO_FILE"
else
    # If it doesn't exist, add it
    echo "$DECO_REQ" >> "$DECO_FILE"
fi

if grep -qF "$ANI_REQ" "$ANI_FILE"; then
    sed -i "/$ANI_REQ/d" "$ANI_FILE"
else
    echo "$ANI_REQ" >> "$ANI_FILE"
fi

hyprctl reload
